public enum MouseAction {
    NONE,
    MOVE,
    CLICK,
    DOUBLE_CLICK,
    SCROLL_UP,
    SCROLL_DOWN,
    DRAG,
    MOVE_TO_ELEMENT,
    CLICK_ON_ELEMENT,
    DOUBLE_CLICK_ON_ELEMENT,
    SCROLL_UP_ON_ELEMENT,
    SCROLL_DOWN_ON_ELEMENT,
    DRAG_ON_ELEMENT,
    HOVER_OVER_ELEMENT,
    RIGHT_CLICK_ON_ELEMENT
}
